# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: production
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
