name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write

    strategy:
      matrix:
        node-version: [20.x, 22.x, 23.x, 24.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: ⏬ switch off autocrlf
        # see https://github.com/actions/checkout/issues/135
        run: git config --global core.autocrlf false

      - name: ⏬ Checkout code
        uses: actions/checkout@v4

      - name: 🔢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⏬ Install
        run: |
          npm install

      - name: ✨ Lint
        run: |
          npm run lint

      - name: 🔨 Build
        run: |
          npm run build

      - name: 🧪 Test
        run: |
          npm test -- --coverage
        env:
          FORCE_COLOR: 1
          JEST_IMAGE_SNAPSHOT_TRACK_OBSOLETE: 1

      - name: 📸 Upload failed screenshot tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tests/__image_snapshots__/__diff_output__/*

      - name: 📈 Coveralls
        continue-on-error: true # this integration is quite buggy
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2.2.3
        with:
          github-token: ${{ secrets.github_token }}

      - name: 📦 Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run trypublish
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
